language: node_js
node_js:
  - "6"
  - "8"
  - "9"
  - "10"
  - "11"

install:
  - npm install
  - npm install -g codecov@3.8.1
  - npm install -g istanbul

before_script:
  - export is_travis=true
script:
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter test -- -R spec
  - codecov

deploy:
  provider: npm
  email: sdk@qiniu.com
  api_key:
    secure: GbKSsROWx6J33WK23cT08eizlkRqpbnCEv3bh4I9R8K5HuUzk08TkNj/LxxuWOEG3hrthivnb5gxshE5UxJ8+nGkS1N2lgZX1i8qT6dGrHb3xda7QB1Szm5+305fCpIa/0jsFqud/8l0GNsNyLezeoaihaNAb9Et5tz6JYVfQxU=
  on:
    tags: true
